version: '3'

services:

  redis:
    image: "redis:4.0.2-alpine"
    restart: "on-failure"
  postgres:
    image: "postgres:9.6.5-alpine"
    restart: "on-failure"
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on: 
      - server
    links:
      - server:redash
    restart: "on-failure"

  server:
    image: "redash/redash"
    command: "server"
    depends_on: 
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
    restart: "on-failure"

  worker:
    image: "redash/redash"
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: "on-failure"
