

services:
  keycloak:
    image: keycloak/keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command: ["start-dev"]

  actix:
    depends_on:
      - keycloak
    build: ./
    ports:
      - 8081:8080
