# Generated by Django 5.2.6 on 2025-09-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataframes',
            name='datasource_id',
        ),
        migrations.AddField(
            model_name='dataframes',
            name='datasource',
            field=models.ForeignKey(db_column='datasource_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dataframes', to='perf.datasource'),
        ),
    ]
