version: '3.7'

services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/mnt/data

volumes:
  postgres_data: