import os

# Connection config of metastore
SUPERSET_METASTORE_USER = os.getenv('SUPERSET_METASTORE_USER', '')
SUPERSET_METASTORE_PASSWORD = os.getenv('SUPERSET_METASTORE_PASSWORD', '')
SUPERSET_METASTORE_HOST = os.getenv('SUPERSET_METASTORE_HOST', '127.0.0.1')
SUPERSET_METASTORE_PORT = os.getenv('SUPERSET_METASTORE_PORT', '3306')
SUPERSET_METASTORE_DATABASE = os.getenv('SUPERSET_METASTORE_DATABASE', 'superset')

SQLALCHEMY_DATABASE_URI = "mysql://{user}:{password}@{host}:{port}/{database}".format(
    user=SUPERSET_METASTORE_USER, password=SUPERSET_METASTORE_PASSWORD,
    host=SUPERSET_METASTORE_HOST, port=SUPERSET_METASTORE_PORT,
    database=SUPERSET_METASTORE_DATABASE
)

# Cache Config
CACHE_TYPE = os.getenv('SUPERSET_CACHE_TYPE', 'simple')
CACHE_DEFAULT_TIMEOUT = os.getenv('SUPERSET_CACHE_DEFAULT_TIMEOUT', 600)
CACHE_THRESHOLD = os.getenv('SUPERSET_CACHE_DEFAULT_TIMEOUT', 1000)
CACHE_DIR=os.getenv('SUPERSET_CACHE_DIR', '/home/superset/cache')
CACHE_KEY_PREFIX = os.getenv('SUPERSET_CACHE_KEY_PREFIX', 'superset')
CACHE_REDIS_URL = os.getenv('SUPERSET_CACHE_REDIS_URL', '')
CACHE_MEMCACHED_SERVERS = [os.getenv('SUPERSET_CACHE_MEMCACHED_SERVERS', '')]
CACHE_CONFIG = {
    'CACHE_TYPE': CACHE_TYPE,
    'CACHE_DEFAULT_TIMEOUT': CACHE_DEFAULT_TIMEOUT,
    'CACHE_THRESHOLD': CACHE_THRESHOLD,
    'CACHE_DIR': CACHE_DIR,
    'CACHE_KEY_PREFIX': CACHE_KEY_PREFIX,
    'CACHE_REDIS_URL': CACHE_REDIS_URL,
    'CACHE_MEMCACHED_SERVERS': CACHE_MEMCACHED_SERVERS
}

SUPERSET_WORKERS = os.getenv('SUPERSET_WORKERS', 1)
SUPERSET_WEBSERVER_PORT = os.getenv('SUPERSET_WEBSERVER_PORT', 8088)

ROW_LIMIT = os.getenv('SUPERSET_ROW_LIMIT', 5000)
SECRET_KEY = os.getenv('SUPERSET_SECRET_KEY', '')