accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Unicode-DFS-2016"
]

targets = ["x86_64-unknown-linux-gnu"]
ignore-build-dependencies = true
ignore-dev-dependencies = true

workarounds = [
    "clap",
    "ring",
    "tonic",
    "prost",
] 