# Generated by Django 5.2.6 on 2025-09-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrames',
            fields=[
                ('dataframe_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataframe_name', models.CharField(max_length=100)),
                ('datasource_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('datasource_id', models.AutoField(primary_key=True, serialize=False)),
                ('datasource_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('file', 'file'), ('database', 'database'), ('url', 'url'), ('folder', 'folder')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.BigIntegerField()),
            ],
        ),
    ]
