// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file service.proto (package sample, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service.proto.
 */
export const file_service: GenFile = /*@__PURE__*/
  fileDesc("Cg1zZXJ2aWNlLnByb3RvEgZzYW1wbGUiFwoHUmVxdWVzdBIMCgRuYW1lGAEgASgJIhsKCFByb2dyZXNzEg8KB3BlcmNlbnQYASABKAUiGQoGUmVzdWx0Eg8KB21lc3NhZ2UYASABKAkigQEKBUVycm9yEiUKBGNvZGUYASABKA4yFy5zYW1wbGUuRXJyb3IuRXJyb3JDb2RlEg8KB21lc3NhZ2UYAiABKAkiQAoJRXJyb3JDb2RlEhoKFkVSUk9SX0NPREVfVU5TUEVDSUZJRUQQABIXChNFUlJPUl9DT0RFX0lOVEVSTkFMEAEieQoIUmVzcG9uc2USJAoIcHJvZ3Jlc3MYASABKAsyEC5zYW1wbGUuUHJvZ3Jlc3NIABIgCgZyZXN1bHQYAiABKAsyDi5zYW1wbGUuUmVzdWx0SAASHgoFZXJyb3IYAyABKAsyDS5zYW1wbGUuRXJyb3JIAEIFCgNyZXMqRAoGU3RhdHVzEhIKDlNUQVRVU19QRU5ESU5HEAASEgoOU1RBVFVTX1JVTk5JTkcQARISCg5NT0RFX1JFQURfT05MWRACMkYKDVNhbXBsZVNlcnZpY2USNQoMU2VydmVyU3RyZWFtEg8uc2FtcGxlLlJlcXVlc3QaEC5zYW1wbGUuUmVzcG9uc2UiADABYgZwcm90bzM");

/**
 * @generated from message sample.Request
 */
export type Request = Message<"sample.Request"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message sample.Request.
 * Use `create(RequestSchema)` to create a new message.
 */
export const RequestSchema: GenMessage<Request> = /*@__PURE__*/
  messageDesc(file_service, 0);

/**
 * @generated from message sample.Progress
 */
export type Progress = Message<"sample.Progress"> & {
  /**
   * @generated from field: int32 percent = 1;
   */
  percent: number;
};

/**
 * Describes the message sample.Progress.
 * Use `create(ProgressSchema)` to create a new message.
 */
export const ProgressSchema: GenMessage<Progress> = /*@__PURE__*/
  messageDesc(file_service, 1);

/**
 * @generated from message sample.Result
 */
export type Result = Message<"sample.Result"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message sample.Result.
 * Use `create(ResultSchema)` to create a new message.
 */
export const ResultSchema: GenMessage<Result> = /*@__PURE__*/
  messageDesc(file_service, 2);

/**
 * @generated from message sample.Error
 */
export type Error = Message<"sample.Error"> & {
  /**
   * @generated from field: sample.Error.ErrorCode code = 1;
   */
  code: Error_ErrorCode;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message sample.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_service, 3);

/**
 * @generated from enum sample.Error.ErrorCode
 */
export enum Error_ErrorCode {
  /**
   * @generated from enum value: ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ERROR_CODE_INTERNAL = 1;
   */
  INTERNAL = 1,
}

/**
 * Describes the enum sample.Error.ErrorCode.
 */
export const Error_ErrorCodeSchema: GenEnum<Error_ErrorCode> = /*@__PURE__*/
  enumDesc(file_service, 3, 0);

/**
 * @generated from message sample.Response
 */
export type Response = Message<"sample.Response"> & {
  /**
   * @generated from oneof sample.Response.res
   */
  res: {
    /**
     * @generated from field: sample.Progress progress = 1;
     */
    value: Progress;
    case: "progress";
  } | {
    /**
     * @generated from field: sample.Result result = 2;
     */
    value: Result;
    case: "result";
  } | {
    /**
     * @generated from field: sample.Error error = 3;
     */
    value: Error;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sample.Response.
 * Use `create(ResponseSchema)` to create a new message.
 */
export const ResponseSchema: GenMessage<Response> = /*@__PURE__*/
  messageDesc(file_service, 4);

/**
 * @generated from enum sample.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_PENDING = 0;
   */
  STATUS_PENDING = 0,

  /**
   * @generated from enum value: STATUS_RUNNING = 1;
   */
  STATUS_RUNNING = 1,

  /**
   * @generated from enum value: MODE_READ_ONLY = 2;
   */
  MODE_READ_ONLY = 2,
}

/**
 * Describes the enum sample.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_service, 0);

/**
 * @generated from service sample.SampleService
 */
export const SampleService: GenService<{
  /**
   * @generated from rpc sample.SampleService.ServerStream
   */
  serverStream: {
    methodKind: "server_streaming";
    input: typeof RequestSchema;
    output: typeof ResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service, 0);

