CREATE FUNCTION text2datetime(str VARCHAR) RETURNS TIMESTAMP WITHOUT TIME ZONE AS $$
BEGIN
   RETURN CAST(str AS TIMESTAMP WITHOUT TIME ZONE);
EXCEPTION WHEN OTHERS THEN
   RETURN NULL;
END;
$$ LANGUAGE plpgsql;


CREATE FUNCTION text2datetime_duck_compat(str VARCHAR) RETURNS TIMESTAMP WITHOUT TIME ZONE AS $$
BEGIN
   RETURN CAST(CAST(str AS TIMESTAMP WITH TIME ZONE) AS TIMESTAMP WITHOUT TIME ZONE);
EXCEPTION WHEN OTHERS THEN
   RETURN NULL;
END;
$$ LANGUAGE plpgsql;
